# Generated by Django 4.2.24 on 2025-10-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_todo_options_todo_due_date_todo_due_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('home', 'Home'), ('personal', 'Personal')], default='personal', max_length=10),
        ),
    ]
